title: Permissionsdispatcher
description: Provides simple annotation-based API to handle runtime permissions in   Android M.
google_analytics: 
show_downloads: true
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
